extends = "/home/ben/auto-battlebot/config/simulation/kinematic_sim"

[mcap]
enable = true

[ui]
enable = false

[transmitter]
behavior_mode = "ATTACK"

[navigation]
type = "MotionProfileNavigation"
hazard_tangent_enable = false
hazard_speed_cap_enable = false
hazard_reverse_distance = 0.0
