"""Loader for simulation/assets/robots/mr_stabs_mk2/mass_properties.toml.

The file is generated by playground/calibration/lump_mr_stabs_mass_properties.py from the
Onshape export. Everything is in the FLU body frame at the axle midpoint.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from auto_battlebot.compat import tomllib

ASSET_DIR = Path(__file__).resolve().parents[2] / "simulation/assets/robots/mr_stabs_mk2"
DEFAULT_PATH = ASSET_DIR / "mass_properties.toml"


@dataclass(frozen=True)
class Body:
    mass: float
    com: np.ndarray  # (3,) m
    fullinertia: np.ndarray  # (6,) Ixx Iyy Izz Ixy Ixz Iyz about the COM, kg m^2

    @classmethod
    def from_table(cls, table: dict[str, Any]) -> Body:
        return cls(
            mass=float(table["mass_kg"]),
            com=np.asarray(table["com_m"], dtype=float),
            fullinertia=np.asarray(table["fullinertia_kg_m2"], dtype=float),
        )


@dataclass(frozen=True)
class TagMount:
    tag_id: int
    upside_down: bool  # faces the floor when the robot is upright
    translation: np.ndarray  # (3,) tag center in the body frame
    rotation: np.ndarray  # (3, 3) R_body_tag
    size_m: float

    def body_from_tag(self) -> np.ndarray:
        out = np.eye(4)
        out[:3, :3] = self.rotation
        out[:3, 3] = self.translation
        return out


@dataclass(frozen=True)
class MassProperties:
    chassis: Body
    wheel_left: Body
    wheel_right: Body
    track_half_width: float
    wheel_radius: float
    tread_width: float
    gear_ratio: float
    motor_kt: float
    rotor_inertia: float
    tags: dict[int, TagMount]

    @property
    def reflected_inertia(self) -> float:
        """Rotor inertia seen at the wheel through the gearbox, N^2 J_r."""
        return self.gear_ratio**2 * self.rotor_inertia

    @property
    def total_mass(self) -> float:
        return self.chassis.mass + self.wheel_left.mass + self.wheel_right.mass


def load(path: Path = DEFAULT_PATH) -> MassProperties:
    data = tomllib.loads(Path(path).read_text())
    geometry = data["geometry"]
    drivetrain = data["drivetrain"]
    tags = {
        int(key): TagMount(
            tag_id=int(key),
            upside_down=bool(t["upside_down"]),
            translation=np.asarray(t["translation_m"], dtype=float),
            rotation=np.asarray(t["rotation"], dtype=float),
            size_m=float(t["size_m"]),
        )
        for key, t in data["tags"].items()
    }
    return MassProperties(
        chassis=Body.from_table(data["chassis"]),
        wheel_left=Body.from_table(data["wheel_left"]),
        wheel_right=Body.from_table(data["wheel_right"]),
        track_half_width=float(geometry["track_half_width_m"]),
        wheel_radius=float(geometry["wheel_radius_m"]),
        tread_width=float(geometry["tread_width_m"]),
        gear_ratio=float(drivetrain["gear_ratio"]),
        motor_kt=float(drivetrain["motor_kt_nm_per_a"]),
        rotor_inertia=float(drivetrain["rotor_inertia_kg_m2"]),
        tags=tags,
    )
