"""Generate the golden-vector fixture for the C++ JigPlantModel test.

Steps the Python reference plant (auto_battlebot/plant.py, `Plant` class: zero-order-hold
command buffer, 2 ms substeps) over a scenario that exercises every term, and writes the
commands plus expected states as a C++ header. The C++ test replays the same commands
through JigPlantModel::propagate and must match: both sides are double precision with the
same substep, so the tolerance can sit at 1e-9.

The scenario covers: quiet start (zero command before the delay elapses), a forward step, a
reversal through the deadzone (decel then accel tau), a pure spin, a combined command that
drives the steer-brake factor into its zero clamp (c_sb 2.70 crosses zero at |u_ang_eff|
0.37), sub-deadzone commands, and a final coast.

Usage:
    source scripts/activate_python.sh
    python playground/calibration/make_plant_golden_fixture.py

Paths are resolved from the repo root, so the working directory does not matter.
"""

from __future__ import annotations

from pathlib import Path

from auto_battlebot.plant import Plant, PlantParams

REPO_ROOT = Path(__file__).resolve().parents[2]
PARAMS_TOML = REPO_ROOT / "playground/calibration/out/plant_stageA.toml"
OUT_HEADER = REPO_ROOT / "tests/robot_filter/plant_golden_data.hpp"

DT = 0.002  # step at the substep size, so each step is exactly one substep on both sides
CMD_TICK_S = 0.02  # command rate, matching the drive CLI
RECORD_STRIDE = 5  # record every 10 ms

# (duration_s, u_lin, u_ang) held segments.
SCENARIO = [
    (0.30, 0.0, 0.0),
    (0.50, 0.5, 0.0),
    (0.40, -0.6, 0.0),
    (0.40, 0.0, 0.4),
    (0.40, 0.5, 0.5),
    (0.20, 0.005, 0.02),
    (0.20, 0.0, 0.0),
]

PARAM_FIELDS = [
    "dz_lin_fwd",
    "dz_lin_rev",
    "dz_ang_l",
    "dz_ang_r",
    "k_fwd",
    "k_rev",
    "k_ang",
    "tau_lin_a",
    "tau_lin_d",
    "tau_ang_a",
    "tau_ang_d",
    "delay_s",
    "c_sb",
    "c_ad",
    "c_drift",
    "c_drift_bias",
]


def fmt(value: float) -> str:
    return f"{value:.17g}"


def emit_array(name: str, values: list[float]) -> str:
    body = ",\n    ".join(", ".join(fmt(v) for v in values[i : i + 4]) for i in range(0, len(values), 4))
    return f"inline constexpr double {name}[] = {{\n    {body},\n}};\n"


def main() -> None:
    params = PlantParams.from_toml(PARAMS_TOML)

    cmd_t: list[float] = []
    cmd_lin: list[float] = []
    cmd_ang: list[float] = []
    t = 0.0
    for duration, u_lin, u_ang in SCENARIO:
        ticks = int(round(duration / CMD_TICK_S))
        for _ in range(ticks):
            cmd_t.append(t)
            cmd_lin.append(u_lin)
            cmd_ang.append(u_ang)
            t += CMD_TICK_S
    total_s = t
    steps = int(round(total_s / DT))

    plant = Plant(params)
    for stamp, u_lin, u_ang in zip(cmd_t, cmd_lin, cmd_ang):
        plant.push_command(stamp, u_lin, u_ang)

    record_steps: list[int] = []
    expected: dict[str, list[float]] = {k: [] for k in ("x", "y", "theta", "v", "w")}
    for step in range(1, steps + 1):
        state = plant.step(DT)
        if step % RECORD_STRIDE == 0:
            record_steps.append(step)
            expected["x"].append(float(state.x))
            expected["y"].append(float(state.y))
            expected["theta"].append(float(state.theta))
            expected["v"].append(float(state.v))
            expected["w"].append(float(state.w))

    lines = [
        "// Generated by playground/calibration/make_plant_golden_fixture.py. Do not edit.",
        f"// Reference: auto_battlebot/plant.py Plant stepping at {fmt(DT)} s, params from",
        f"// {PARAMS_TOML.relative_to(REPO_ROOT)}.",
        "#pragma once",
        "",
        "namespace auto_battlebot::plant_golden {",
        "",
        f"inline constexpr double kDt = {fmt(DT)};",
        f"inline constexpr int kSteps = {steps};",
        f"inline constexpr int kRecordStride = {RECORD_STRIDE};",
        "",
    ]
    for field in PARAM_FIELDS:
        lines.append(f"inline constexpr double kParam_{field} = {fmt(getattr(params, field))};")
    lines.append("")
    lines.append(f"inline constexpr int kNumCommands = {len(cmd_t)};")
    lines.append(emit_array("kCmdStamp", cmd_t))
    lines.append(emit_array("kCmdLin", cmd_lin))
    lines.append(emit_array("kCmdAng", cmd_ang))
    lines.append(f"inline constexpr int kNumRecords = {len(record_steps)};")
    lines.append("// Record r is the state after kRecordStride * (r + 1) steps, theta unwrapped.")
    lines.append(emit_array("kExpectedX", expected["x"]))
    lines.append(emit_array("kExpectedY", expected["y"]))
    lines.append(emit_array("kExpectedTheta", expected["theta"]))
    lines.append(emit_array("kExpectedV", expected["v"]))
    lines.append(emit_array("kExpectedW", expected["w"]))
    lines.append("}  // namespace auto_battlebot::plant_golden")
    lines.append("")

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_HEADER} ({len(record_steps)} records over {fmt(total_s)} s)")


if __name__ == "__main__":
    main()
