#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

# SIGINT-handler
int_handler() {
    echo "Caught stop signal"
    if [ -n "$SIM_PID" ]; then
        echo "Stopping simulation"
        kill -SIGINT "${SIM_PID}"
        tail --pid="${SIM_PID}" -f /dev/null
    fi
    exit 0;
}
trap 'int_handler' SIGINT

RUN_HEADLESS=false
SUPPLIMENTAL_ARGS=()

for arg in "$@"; do
    if [ "$arg" == "--headless" ]; then
        RUN_HEADLESS=true
    elif [ "$arg" == "--help" ] || [ "$arg" == "-h" ]; then
        echo "Usage: run_simulation [--headless] [--scenario <scenario_name>]"
        exit 0
    else
        SUPPLIMENTAL_ARGS+=("$arg")
    fi
done

if [ "$RUN_HEADLESS" == true ]; then
    SIMULATION_ARGS="-nographics -batchmode"
else
    SIMULATION_ARGS=""
fi

EXTENSION=$(uname -i)
${BASE_DIR}/../auto-battlebot-sim/Build/auto-battlebot-sim.${EXTENSION} ${SIMULATION_ARGS} ${SUPPLIMENTAL_ARGS[@]} -logFile /tmp/auto-battlebot-sim.log &
SIM_PID=$!

tail -F -n 1 /tmp/auto-battlebot-sim.log
