extends = "_desktop"

[robot_filter.label_mapping]
"MRS_BUFF_MK3" = ["THEIR_ROBOT_1"]
"MR_STABS_MK2" = ["OUR_ROBOT_1"]

[robot_mask_model]
their_robot_labels = ["OPPONENT", "MRS_BUFF_MK3"]

[navigation]
type = "PursuitNavigation"
angular_kp = 0.2
angular_kd = 0.01
max_linear_x = 0.2         # 0 = no limit

[transmitter]
wheel_track_width = 0.131
max_motor_rpm = 2000            # RPM
lifted_deadzone_percent = 0
zero_deadzone_percent = 2
reverse_angular_channel = true
velocity_saturation_limit = 1.0 # 0 = disabled; e.g. 1.0 = |linear| + |angular| <= 1
