extends = "simulation/kinematic_sim"

[mcap]
enable = true

[ui]
enable = false

[field_filter]
size_x = 1.48
size_y = 1.41

[transmitter]
behavior_mode = "ATTACK"

[navigation]
type = "MotionProfileNavigation"
