[platformio]
default_envs = qtpy_esp32s3
src_dir = .

[env:qtpy_esp32s3]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
lib_deps =
    plerup/espsoftwareserial
build_flags =
    -I ESP32
build_src_filter =
    +<src/main.cpp>
    +<ESP32/4Way.cpp>
    +<ESP32/MSP.cpp>
    +<ESP32/serial_comm.cpp>
    +<ESP32/ESC_Serial.cpp>
    +<ESP32/Global.cpp>
