#!/usr/bin/env bash
# Routed board -> JLCPCB upload files. Run from this directory after SKILL/scripts/flow.sh mk2.
#   ./make_fab.sh
# 1. silk.py: labels, Mk2 and BWBots art, via-field tenting (flow.sh rebuilds the board each try,
#    so these go on after routing).
# 2. check.sh: DRC, exits 1 on any error or unconnected item.
# 3. fab.sh: fab/gerbers.zip, fab/bom.csv, fab/cpl.csv.
# 4. Drop BOM rows with no LCSC number: wire pads and the via field are copper, not parts.
# 5. schematic.py (connectivity checked against mk2.net) and render_3d.py, then the review page.
set -euo pipefail
S=/home/ben/.claude/plugins/cache/pcba-skill/pcba-design/0.1.0/skills/pcba-design
"$S/scripts/kicad" python3 silk.py mk2_routed.kicad_pcb
"$S/scripts/check.sh" mk2_routed.kicad_pcb
"$S/scripts/fab.sh" mk2_routed.kicad_pcb mk2.net fab
python3 - <<'PY'
import csv
rows = list(csv.reader(open("fab/bom.csv")))
keep = [rows[0]] + [r for r in rows[1:] if r[3].strip()]
csv.writer(open("fab/bom.csv", "w", newline="")).writerows(keep)
print(f"bom.csv: {len(keep) - 1} lines with LCSC numbers, {len(rows) - len(keep)} copper-only rows dropped")
PY
"$S/scripts/kicad" python3 "$S/scripts/schematic.py" mk2.net placement.json
# KiCad ships no model for L1's NR-40xx footprint; render_3d.py adds art/models/fnr4030_inductor.
python3 "$S/scripts/fetch_3dmodels.py" mk2_routed.kicad_pcb || true
"$S/scripts/kicad" python3 render_3d.py
"$S/scripts/run" page.py . --title "Mr Stabs Mk2 board" --note "${NOTE:-regenerated by make_fab.sh}"
