# Converts a binary file into a C++ source that defines <SYMBOL>[] and <SYMBOL>_size.
# Invoked at build time by the embed_brand_asset() helper in the top-level CMakeLists:
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P cmake/bin2c.cmake

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hex_len)
math(EXPR _size "${_hex_len} / 2")

# 0x-prefix each byte, 16 bytes per line.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" _bytes "${_bytes}")

get_filename_component(_input_name "${INPUT}" NAME)
file(WRITE "${OUTPUT}"
"// Generated by cmake/bin2c.cmake from ${_input_name} (${_size} bytes). Do not edit.
#include <cstddef>
#include <cstdint>

extern const uint8_t ${SYMBOL}[];
extern const size_t ${SYMBOL}_size;

const uint8_t ${SYMBOL}[] = {
${_bytes}
};
const size_t ${SYMBOL}_size = ${_size};
")
