#!/usr/bin/env python3
"""Bake the BW Bots splash GIF into a 1-bit OLED animation header.

Uses the pre-cropped 128x64 GIF as-is (no crop, scale, or filtering). The source
has 3 gray levels: 0 maps to black; 204 (the gray outline) and 255 map to white.

Writes include/splash_anim.h. Add --preview <png> for a montage.
Regenerate with: scripts/make_splash.py
"""
import os
import sys

from PIL import Image

GIF = "/home/ben/Downloads/bwbots_splash_crop.gif"
W, H = 128, 64
THRESH = 204          # 0 -> black; 204 (gray outline) and 255 -> white
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "..", "include", "splash_anim.h")


def pack(img1):
    px = img1.load()
    row_bytes = (W + 7) // 8
    out = bytearray()
    for y in range(H):
        for bx in range(row_bytes):
            b = 0
            for bit in range(8):
                x = bx * 8 + bit
                if x < W and px[x, y]:
                    b |= 1 << (7 - bit)
            out.append(b)
    return out


def main():
    im = Image.open(GIF)
    n = im.n_frames

    # Source is already cropped to the display; use each frame as-is (centered if
    # it happens to be smaller than 128x64).
    ox, oy = (W - im.size[0]) // 2, (H - im.size[1]) // 2

    frames, packed = [], []
    for i in range(n):
        im.seek(i)
        canvas = Image.new("L", (W, H), 0)
        canvas.paste(im.convert("L"), (ox, oy))
        out = canvas.point(lambda p: 255 if p >= THRESH else 0).convert("1")
        frames.append(out)
        packed.append(pack(out))

    row_bytes = (W + 7) // 8
    with open(OUT_H, "w") as f:
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write("// Generated by scripts/make_splash.py from bwbots_splash.gif\n")
        f.write("#define SPLASH_W %d\n#define SPLASH_H %d\n#define SPLASH_FRAMES %d\n\n"
                % (W, H, n))
        f.write("static const uint8_t SPLASH_DATA[SPLASH_FRAMES][%d] PROGMEM = {\n"
                % (H * row_bytes))
        for pk in packed:
            f.write("  {" + ",".join("0x%02x" % b for b in pk) + "},\n")
        f.write("};\n")
    print("wrote %s (%d frames, %dx%d @ %d,%d)" % (OUT_H, n, im.size[0], im.size[1], ox, oy))

    if "--preview" in sys.argv:
        cols = 6
        rows = (n + cols - 1) // cols
        sheet = Image.new("L", (cols * (W + 4), rows * (H + 4)), 60)
        for i, fr in enumerate(frames):
            r, c = divmod(i, cols)
            sheet.paste(fr.convert("L"), (c * (W + 4) + 2, r * (H + 4) + 2))
        p = sys.argv[sys.argv.index("--preview") + 1]
        sheet.resize((sheet.width * 2, sheet.height * 2), Image.NEAREST).save(p)
        print("preview ->", p)


if __name__ == "__main__":
    main()
