#!/bin/bash
# Plot + summarize a velocity-jig LOG file: plot data/downloads/LOG-1.TXT [--show]
BASE_DIR=$(realpath "$(dirname "$0")")
exec "${BASE_DIR}/../../../venv/bin/python" "${BASE_DIR}/plot_log.py" "$@"
