[rgbd_camera]
type = "SimRgbdCamera"
tcp_host = "127.0.0.1"
tcp_port = 18707
tcp_connect_timeout_ms = 5000
tcp_read_timeout_ms = 1000
tcp_auto_reconnect = true

[field_model]
type = "DeepLabMaskModel"
model_path = "models/field_deeplabv3_r50_2024-09-05_x86_64.engine"

[robot_mask_model]
type = "DeepLabMaskModel"
model_path = "models/floor_deeplabv3_mbv3_256x256_x86_64.engine"
output_label = "OPPONENT"

[field_filter]
type = "PointCloudFieldFilter"
local_visualize_debug = false
distance_threshold = 0.1

[keypoint_model]
type = "YoloKeypointModel"
model_path = "models/yolo26x-pose_synthetic_only_2026-02-02_x86_64.engine"
label_indices = ["MR_STABS_MK2"]
debug_visualization = false
threshold = 0.5

[[keypoint_model.label_map]]
label = "MR_STABS_MK1"
keypoints = ["MR_STABS_MK1_FRONT", "MR_STABS_MK1_BACK"]

[[keypoint_model.label_map]]
label = "MR_STABS_MK2"
keypoints = ["MR_STABS_MK2_FRONT", "MR_STABS_MK2_BACK"]

[[keypoint_model.label_map]]
label = "MRS_BUFF_MK1"
keypoints = ["MRS_BUFF_MK1_FRONT", "MRS_BUFF_MK1_BACK"]

[[keypoint_model.label_map]]
label = "MRS_BUFF_MK2"
keypoints = ["MRS_BUFF_MK2_FRONT", "MRS_BUFF_MK2_BACK"]

[[keypoint_model.label_map]]
label = "HOUSE_BOT"
keypoints = ["HOUSE_BOT_FRONT", "HOUSE_BOT_BACK"]

[[keypoint_model.label_map]]
label = "OPPONENT"
keypoints = ["OPPONENT_FRONT", "OPPONENT_BACK"]

[robot_filter]
type = "RobotFrontBackSimpleFilter"
default_frame_id = "OUR_ROBOT_1"

front_keypoints = [
    "MR_STABS_MK1_FRONT",
    "MR_STABS_MK2_FRONT",
    "MRS_BUFF_MK1_FRONT",
    "MRS_BUFF_MK2_FRONT",
    "HOUSE_BOT_FRONT",
    "OPPONENT_FRONT",
]
back_keypoints = [
    "MR_STABS_MK1_BACK",
    "MR_STABS_MK2_BACK",
    "MRS_BUFF_MK1_BACK",
    "MRS_BUFF_MK2_BACK",
    "HOUSE_BOT_BACK",
    "OPPONENT_BACK",
]

[robot_filter.label_mapping]
"MR_STABS_MK1" = ["OUR_ROBOT_1"]
"MR_STABS_MK2" = ["OUR_ROBOT_1"]
"MRS_BUFF_MK1" = ["OUR_ROBOT_2"]
"MRS_BUFF_MK2" = ["OUR_ROBOT_2"]
"HOUSE_BOT" = ["NEUTRAL_ROBOT_1"]
"OPPONENT" = ["THEIR_ROBOT_1", "THEIR_ROBOT_2", "THEIR_ROBOT_3"]

[navigation]
type = "PursuitNavigation"

[transmitter]
type = "SimTransmitter"

[publisher]
type = "RosPublisher"

[runner]
max_loop_rate = 300.0
